### ISSUE TITLE
feature request: Add `author` field.

### ISSUE THREAD

**Issue by molingyu** [phodal/adr#1]
Add `author` field in decision record.

### In template:
```markdown
## Author
[author-name](mailto:name@email.com)
```
### ` author ` command
```
adr author name
```
Search adr by author.

**Comment by phodal** [comment]
Hi,

The ``author`` will be see by ``git log``, and the ADR will be manage in same team, why you need it?

**Comment by molingyu** [comment]
thxs, many non-technical people are in my team,so....

I will keep a private version of use author field in my branch.
