### ISSUE TITLE
Add trailing newline to TOC

### ISSUE THREAD

**Issue by dreh23** [phodal/adr#17]
* **I'm submitting a ...**
[ X] feature request

* **Summary**
The autogenerated TOC has no trailing newline.

This is problematic if you run a markdown linter that lints according to the commonmark spec. Since we autogenerate (adr -u) the TOC and we do linting in a continuous integration context this always fails.

A flag for adr -u to add a newline after generation would be useful.

`README.md:3 MD047/single-trailing-newline Files should end with a single newline character`

As a workaround I changed line [47](https://github.com/phodal/adr/blob/master/src/lib/update.ts#L47) to following:

`fs.writeFileSync(savePath + 'README.md', toc + "\n");`

This is not very elegant and maybe not be platform independent.

As reference I filed an issue in the wrong repo first [see](https://github.com/adr/madr/issues/26)

**Comment by phodal** [comment]
hello, PR is welcome
