### ISSUE TITLE
No such file docs/adr/undefined

### ISSUE THREAD

**Issue by matmilbury** [phodal/adr#27]
* **I'm submitting a ...**
[ ] language request
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
I have just one DR.

I execute `yarn adr list 2`

I get an error `Error: ENOENT: no such file or directory, open 'docs/adr/undefined'`

**Comment by phodal** [comment]
Thanks for issue. I'm not sure is it execute `adr list`, it could be `adr status 2`.

Any suggest for this error? In current design, adr just believe dev can know item is exists.

**Comment by matmilbury** [comment]
Oh, sorry. The failing command was `yarn adr logs 2`
