### ISSUE TITLE
adr export Markdown fails

### ISSUE THREAD

**Issue by matmilbury** [phodal/adr#28]
* **I'm submitting a ...**
[ ] language request
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
`yarn adr help export` says: 'export ADR reporter in HTML, CSV, JSON, Markdown'

but

`yarn adr export Markdown` fails

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by phodal** [comment]
sorry, it don't support markdown
