### ISSUE TITLE
Custom template.md is included in the html export 

### ISSUE THREAD

**Issue by matmilbury** [phodal/adr#29]
* **I'm submitting a ...**
[ ] language request
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Custom template.md is included in the html export 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by phodal** [comment]
Would you like to have a PR to fix this?
