### ISSUE TITLE
Does it miss the important step after using the command `adr new`

### ISSUE THREAD

**Issue by reply2future** [phodal/adr#34]
* **I'm submitting a ...**
[ ] language request
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**

As `README.md` mentioned, there is no other informations to explain how to do next after using `adr new ` command. It's confused and console prints the save directory path. So I think it's important to add more informations what to do next.

I found `adr-tools` using the [environment variable](https://github.com/npryce/adr-tools/blob/b3279baf9be2207d1a4f4bbd608fd0b591c72aee/src/adr-new#L132) to open new file with which editor, so it would be better to use some package(such as [open-in-editor](https://github.com/lahmatiy/open-in-editor)) to implement this feature and adding the editor configuration.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
1. [open-in-editor](https://github.com/lahmatiy/open-in-editor)
2. [launch-editor](https://github.com/yyx990803/launch-editor)

**Comment by phodal** [comment]
would you like to create a pr for this?

**Comment by reply2future** [comment]
> would you like to create a pr for this?

Okay,I will try it
