### ISSUE TITLE
Asset compression support

### ISSUE THREAD

**Issue by AmirAsghary** [phodal/adr#36]
* **I'm submitting a ...**
[X] feature request

* **Summary**
What do you think about adding support for asset-compression (images specifically)? 

The total asset size for ADR can get out of hand over time. 

We added a basic image compression system to our repo for ADRs using the [sharp](https://www.npmjs.com/package/sharp) library with caching in mind. I can work on adding it to this library as well.

**Comment by phodal** [comment]
Yes, you can try to do it.
