### ISSUE TITLE
$ adr command not found in version 1.4.2

### ISSUE THREAD

**Issue by max-arshinov** [phodal/adr#45]
* **I'm submitting a ...**
[ ] language request
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
* npm i adr -g
* adr

##  Expected 
* $adr -> shows info
##  Actual
* $ adr ->  command not found: adr

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Perhaps, this is because "build" folder is missing in version 1.4.2: https://registry.npmjs.org/adr/-/adr-1.4.2.tgz
V 1.4.1. works as expected: https://registry.npmjs.org/adr/-/adr-1.4.1.tgz

<img width="267" alt="image" src="https://user-images.githubusercontent.com/820550/193692639-6842b9c9-c0af-4775-b5b6-bcac94869866.png">

**Comment by phodal** [comment]
sorry for that, already publish 1.4.3
